### ISSUE TITLE
Vignettes

### ISSUE THREAD

**Issue by Biomiha** [immunogenomics/starCAT#2]
Hi,

I've tried to find either the python or the R vignettes but both links seem to be broken. Would you be able to share again please?
Looking forward to trying the tool.
Thank you in advance.

**Comment by dylkot** [comment]
Hi @Biomiha, hmm I'm not seeing broken links on my end. Do either of these work for you?

https://github.com/immunogenomics/starCAT/blob/main/Examples/starCAT_vignette.ipynb

https://github.com/immunogenomics/starCAT/blob/main/Examples/starCAT_vignette_R.ipynb

Thanks,
Dylan

**Comment by Biomiha** [comment]
Hi @dylkot,

Yes, thank you very much. These both work fine for me. 
I was referring to the links on the main page ([python](https://github.com/immunogenomics/starCAT/blob/main/Examples/starCAT_vingette.ipynb) and [R](https://github.com/immunogenomics/starCAT/blob/main/Examples/starCAT_vingette_R.ipynb)) where I get 404 - page not found errors for both.

Many thanks again.
Miha

**Comment by dylkot** [comment]
Gotcha, I don't fully understand what was going wrong with the links but I fixed them now. Thank you!
