### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

### ISSUE THREAD

**Issue by JiahuaQu** [immunogenomics/starCAT#3]
Hi, thank you for the new program. When I was trying it in Linux system within a conda env, I got the error first:
`  File "/home/.conda/envs/starCAT_env/lib/python3.9/site-packages/starcat/starcat.py", line 417, in save_results
    self.usage_norm.to_csv(os.path.join(output_dir, name+'.rf_usage_normalized.txt'), sep='\t')
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`.
Then I revised the line of script manually to be `name, '.rf_usage_normalized.txt')`. Although the program progressed a little, I had another similar error:
`  File "/home/.conda/envs/starCAT_env/lib/python3.9/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'`

I also tried to install another version of python (3.7) which was tested by you, but it didn't work either.

Hope to get your help to figure it out. Thank you.

**Comment by michelle-curtis** [comment]
Hi, thanks for your post! Could you provide the full set of commands you are running, and the full error traces?

**Comment by JiahuaQu** [comment]
Thank you for your quick response.
My commands:
`ref="TCAT.V1"
counts_fn="01-make_mtx/matrix.mtx.gz"
ouput_name="starCAT-CARneg"
output_dir="02-run_starCAT"
if [ ! -d "${output_dir}" ]; then
  mkdir "${output_dir}"
fi
starcat --reference $ref --counts ${counts_fn} --output-dir ${output_dir} --name ${output_name}`

**Comment by michelle-curtis** [comment]
Thank you! I think it might be a typo when assigning the variable  `output_name`. Can you try changing `ouput_name="starCAT-CARneg"` to `output_name="starCAT-CARneg"'`, and see if that solves the issue, when running the original code?

**Comment by michelle-curtis** [comment]
The arguments `score_path` and `cachedir` actually aren't supported when running starcat via command line. You can find a list of possible command line arguments in the README.md. The argument to specify a scores.yml file via command line is `--scores`, so an example command would look like this: 
`starcat --reference "TCAT.V1" --counts {counts_fn} --output-dir {output_dir} --name {outuput_name} --scores {score_path}`

Also, please note that including a scores file is optional. If you are using the default TCAT.V1 reference, you can just specify its name `--reference "TCAT.V1"`, and both the reference and scores paths can be inferred from this. In this case, the reference and scores file will be downloaded to a cache location in your working directory, i.e `'./cache'`. 

Hope this helps!

**Comment by JiahuaQu** [comment]
Thank you very much. I ran the program successfully and will delve into the results.

**Comment by michelle-curtis** [comment]
Ok great!
