### ISSUE TITLE
Annotating after integration

### ISSUE THREAD

**Issue by Jon-bioinfo** [immunogenomics/starCAT#5]
If the input data to annotate are from multiple expermients/conditions/etc does that affect the results
i.e. would you ideally annotate before combining, or no effect?

Also I had to `pip install requests` after `pip install starcatpy` in a fresh conda env. Could be added to the dependencies.

**Comment by dylkot** [comment]
Hi @Jon-bioinfo, thanks for using starCAT!

The results should be pretty robust to data from multiple experiments/conditions. Many artifact variables are incorporated in the T-cell GEP catalog (e.g. the intermediate early genes or the MALAT1 signal) in which case, cells from the different conditions might have higher use of one of those artifact GEPs. But the loadings of the other non-artifact GEPs are usually pretty robust. You might double check if there are any systematic differences in their usage across conditions that seem sketchy to you. Batch signals that are orthogonal to the GEPs should not impact the results.

Thank you, yes I will add ```requests``` to the dependencies
