### ISSUE TITLE
Reference for B cell subtypes.

### ISSUE THREAD

**Issue by zhanzmr** [immunogenomics/starCAT#6]
Hi, Thanks for this great tool! Just wondering is there a GEP reference for B cell subset (Naive, un/switch-memory, plasmablast)? Or any ways to do a B cell subtype annotation using this tool? Thanks so much!

**Comment by dylkot** [comment]
Hi, thanks for checking out starCAT. I am actively working on a B-cell reference and will keep you updated when it is ready. Cheers,
Dylan
